// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMo_-481VvnB5dMbItn6j9fIL7LfQsNj0',
    appId: '1:908015164698:web:0a499ca5e8763acf97a0a3',
    messagingSenderId: '908015164698',
    projectId: 'unialert-0',
    authDomain: 'unialert-0.firebaseapp.com',
    storageBucket: 'unialert-0.appspot.com',
    measurementId: 'G-27CYS238Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHN-eoTEQPw9bZcKhhSw2zCe0RsRpObk',
    appId: '1:908015164698:android:839efa55490aaeeb97a0a3',
    messagingSenderId: '908015164698',
    projectId: 'unialert-0',
    storageBucket: 'unialert-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALnIzY7GquPXScsfZ57Ka9Z6e0Ns9Q1oc',
    appId: '1:908015164698:ios:407be6f21ae91e6a97a0a3',
    messagingSenderId: '908015164698',
    projectId: 'unialert-0',
    storageBucket: 'unialert-0.appspot.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
